### PR TITLE
Feat: Docker Revamp + Dependency Upgrade

### PR DESCRIPTION
**Pull request by cawfeecoder**
# Description
- This updates a load of dependencies (the only one that can't go to latest is Prometheus due to a regression in prometheus-rs)
- This modifies the Dockerfile to be build using musl (for security purposes), restricts the running user to 'graphgate' (security), and uses jemalloc (for performance purposes).

### CODE REVIEW

**Comment by cawfeecoder** [comment]
@sunli829 Here's the Dockerfile revamp I talked about in my other PR

**Comment by cawfeecoder** [comment]
@sunli829 Can you take a look and tell me why lifetimes are getting flagged in the examples?

**Comment by sunli829** [comment]
This seems to be caused by a bug in `Async-graphql v3`, I'm checking.

**Comment by sunli829** [comment]
Fixed in async-graphql `v3.0.24`

**Comment by cawfeecoder** [comment]
@sunli829 This looks ready to merge :)

**Comment by sunli829** [comment]
Thanks! 😁

**Pull request merged**
